//! Agent identity — the principal leti-core knows about.
//!
//! Core is host-identity-blind by design. External ownership and routing
//! concepts live in the host layer. Plugins map their context to an
//! `AgentId` before invoking core.
//!
//! Invariant: **one agent owns exactly one workspace.** Multi-workspace
//! routing belongs in a plugin that wraps core, not core itself.

use std::fmt;
use std::path::PathBuf;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Stable agent identifier (UUIDv4). Wire format is the canonical
/// hyphenated string. Generated by core for self-hosted boots; cloud
/// plugins pre-allocate via the user→agent ownership table.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct AgentId(pub Uuid);

impl AgentId {
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    #[must_use]
    pub fn as_uuid(&self) -> Uuid {
        self.0
    }
}

impl Default for AgentId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for AgentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<Uuid> for AgentId {
    fn from(v: Uuid) -> Self {
        Self(v)
    }
}

impl FromStr for AgentId {
    type Err = uuid::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Uuid::parse_str(s).map(Self)
    }
}

/// Boot-time agent declaration. One per agent registered on `AppState`.
/// `workspace_root` is the local hint — cloud adapters override the
/// effective root inside their own `Filesystem` impl.
#[derive(Debug, Clone)]
pub struct AgentSpec {
    pub id: AgentId,
    pub workspace_root: PathBuf,
    pub display_name: String,
}

impl AgentSpec {
    #[must_use]
    pub fn new(id: AgentId, workspace_root: PathBuf, display_name: impl Into<String>) -> Self {
        Self {
            id,
            workspace_root,
            display_name: display_name.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_via_string() {
        let a = AgentId::new();
        let s = a.to_string();
        let b: AgentId = s.parse().expect("parse");
        assert_eq!(a, b);
    }

    #[test]
    fn rejects_non_uuid() {
        assert!("not-a-uuid".parse::<AgentId>().is_err());
    }
}
