/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/agent` */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/diagnostics` */
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/files?query=` — list/search workspace files. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/files/content?path=` — read a workspace file's content. */
        get: operations["content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health-check handler. Always returns 200 once the server is bound. */
        get: operations["handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /v1/models`
         * @description Delegates to [`ModelProvider::list_models`]. Providers without a
         *     catalog (mock, single-model gateways) return `[]` via the trait's
         *     default impl, so this route is always 200 on a reachable provider and
         *     only surfaces an error when the upstream call itself fails (network,
         *     auth, rate-limit).
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permission/{ask_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugin/{id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/session` — list sessions (excluding deleted by default). */
        get: operations["list"];
        put?: never;
        /** `POST /v1/session` — create session. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/session/:id` — fetch one session. */
        get: operations["get_one"];
        put?: never;
        post?: never;
        /** `DELETE /v1/session/:id` — soft-delete. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/session/:id/mode` — change permission mode. */
        post: operations["set_mode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/prompt_async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prompt_async"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}/question/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description `POST /v1/session/:id/abort` ack. */
        AbortAckDto: {
            aborted: boolean;
        };
        /** @description Public-facing description of a registered agent. */
        AgentDto: {
            /**
             * Format: float
             * @description Fraction of `context_window` at which auto-compaction fires. Lets
             *     the client mark "left until compact" rather than the hard limit.
             */
            compaction_threshold: number;
            /**
             * Format: int32
             * @description Total token budget of the agent's model. Denominator for the
             *     client's context-usage indicator; sourced from the agent
             *     definition (`AgentSpec` carries no tuning, same as `model`).
             */
            context_window: number;
            display_name: string;
            /** Format: uuid */
            id: string;
            /**
             * @description The model the serve path actually runs for this agent's turns.
             *     `AgentSpec` carries no per-agent model; turns resolve the
             *     effective model from `config.default_model`, so the route fills
             *     this with that value to avoid showing a model the turn never uses.
             */
            model: string;
            workspace_root: string;
        };
        /** @description Wire shape for an `ask_user` option. */
        AskOptionDto: {
            description?: string | null;
            label: string;
        };
        /** @description Response body for a successful upload. */
        AttachmentAck: {
            artifact_id: string;
            kind: string;
            /** Format: uuid */
            message_id: string;
            mime: string;
            /** Format: uuid */
            part_id: string;
            summary: string;
        };
        /**
         * @description Wire shape for `AttachmentKind`. Mirrors the domain enum 1:1.
         * @enum {string}
         */
        AttachmentKindDto: "image" | "document";
        CheckResult: {
            detail?: string | null;
            /** Format: int64 */
            elapsed_ms: number;
            name: string;
            status: components["schemas"]["Status"];
        };
        /**
         * @description `POST /v1/session/:id/compact` ack. `compacted` is false when there was
         *     nothing to compact (conversation at/under the preserved-recent floor).
         */
        CompactAckDto: {
            compacted: boolean;
        };
        /** @description `POST /v1/session/:id/prompt_async` body. */
        CreateMessageDto: {
            parts: components["schemas"]["PartDto"][];
        };
        /**
         * @description `POST /v1/session` body. `agent_id` may be omitted to use the
         *     server's default agent (single-agent self-hosted boot).
         *
         *     `extensions` is an opaque integrator-owned JSON blob (e.g.
         *     `{"user_id": "u_123", "tenant_id": "t_42"}`). Core stays auth-blind:
         *     the schema lives entirely in the integrator. Defaults to `null`.
         *
         *     `user_questions` declares whether the caller can answer interactive
         *     `ask_user` prompts. Defaults to `true` because this DTO is used by
         *     interactive frontends (the TUI); headless callers set it `false` so
         *     `ask_user` fails fast instead of blocking on a UI that never replies.
         */
        CreateSessionDto: {
            /** Format: uuid */
            agent_id?: string | null;
            extensions?: Record<string, never>;
            /** Format: uuid */
            parent_session_id?: string | null;
            permission_mode?: null | components["schemas"]["PermissionMode"];
            user_questions?: boolean;
        };
        /** @enum {string} */
        DeltaKindDto: "text" | "reasoning" | "tool_args";
        DoctorReport: {
            checks: components["schemas"]["CheckResult"][];
            overall: components["schemas"]["Status"];
        };
        /**
         * @description Stable error envelope. `code` is a `&'static str` slug from
         *     `FailureClass::as_str` (or a route-local slug); `message` is a
         *     human-readable detail. `details` carries optional structured context
         *     (validation errors, etc.).
         */
        ErrorDto: {
            /** @example session_not_found */
            code: string;
            details?: unknown;
            /** @example session 7f… not found */
            message: string;
        };
        /**
         * @description SSE-encoded frame envelope. Server emits `id:` (events.id) +
         *     `event:` (kind) + `data:` (`AgentEvent` JSON).
         */
        EventDto: {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "session_status";
            /** Format: uuid */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        } | {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "message_created";
            /** Format: uuid */
            message_id: string;
            /** Format: uuid */
            session_id: string;
        } | {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "part_created";
            /** Format: uuid */
            message_id: string;
            /** Format: uuid */
            part_id: string;
            /** Format: uuid */
            session_id: string;
        } | {
            delta: string;
            delta_kind: components["schemas"]["DeltaKindDto"];
            /** @enum {string} */
            kind: "part_delta";
            /** Format: uuid */
            message_id: string;
            /** Format: uuid */
            part_id: string;
            /** Format: uuid */
            session_id: string;
        } | {
            /** @enum {string} */
            kind: "part_updated";
            /** Format: uuid */
            message_id: string;
            /** Format: uuid */
            part_id: string;
            /** Format: uuid */
            session_id: string;
        } | {
            cost_decimal_str?: string | null;
            /** @enum {string} */
            kind: "step_finished";
            /** Format: uuid */
            message_id: string;
            reason: string;
            /** Format: uuid */
            session_id: string;
            usage?: null | components["schemas"]["UsageDto"];
        } | {
            /** @enum {string} */
            kind: "permission_asked";
            request: components["schemas"]["PermissionRequestDto"];
            /** Format: uuid */
            session_id: string;
        } | {
            /** Format: uuid */
            ask_id: string;
            decision: components["schemas"]["PermissionDecisionDto"];
            /** @enum {string} */
            kind: "permission_resolved";
            /** Format: uuid */
            session_id: string;
        } | {
            code: string;
            /** @enum {string} */
            kind: "error";
            message: string;
            /** Format: uuid */
            session_id?: string | null;
        } | {
            hook: string;
            /** @enum {string} */
            kind: "plugin_error";
            message: string;
            plugin_id: string;
            /** Format: uuid */
            session_id?: string | null;
        } | {
            header: string;
            /** @enum {string} */
            kind: "question_requested";
            multi_select: boolean;
            options: components["schemas"]["AskOptionDto"][];
            question: string;
            /** Format: uuid */
            question_id: string;
            /** Format: uuid */
            session_id: string;
        } | {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "plan_mode_entered";
            /** Format: uuid */
            session_id: string;
        } | {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "plan_mode_exited";
            plan: string;
            /** Format: uuid */
            session_id: string;
        } | {
            artifact_id: string;
            attachment_kind: components["schemas"]["AttachmentKindDto"];
            /** @enum {string} */
            kind: "attachment_accepted";
            /** Format: uuid */
            message_id: string;
            mime: string;
            /** Format: uuid */
            part_id: string;
            /** Format: uuid */
            session_id: string;
            summary: string;
        } | {
            /** @enum {string} */
            kind: "subagent_started";
            /** Format: uuid */
            parent_session_id: string;
            subagent_type: string;
            /** Format: uuid */
            task_id: string;
        } | {
            delta: string;
            /** @enum {string} */
            kind: "subagent_output";
            /** Format: uuid */
            parent_session_id: string;
            /** Format: uuid */
            task_id: string;
        } | {
            cost_usd?: string | null;
            /** @enum {string} */
            kind: "subagent_finished";
            output: string;
            /** Format: uuid */
            parent_session_id: string;
            /** Format: uuid */
            task_id: string;
        } | {
            body: string;
            /** @enum {string} */
            kind: "notification_emitted";
            level: components["schemas"]["NotificationLevelDto"];
            plugin_id: string;
            /** Format: uuid */
            session_id?: string | null;
            title: string;
        } | {
            /** @enum {string} */
            kind: "heartbeat";
        };
        FileContentDto: {
            /** @description Embeddable text content. Absent for unsupported (binary) types. */
            content?: string | null;
            path: string;
            /** @description True when content was clamped to the server's size cap. */
            truncated?: boolean;
            type: components["schemas"]["FileKindDto"];
            /** @description True for types whose content cannot be embedded as text (image/pdf). */
            unsupported?: boolean;
        };
        FileEntryDto: {
            path: string;
            type: components["schemas"]["FileKindDto"];
        };
        /**
         * @description File classification surfaced to the client (drives badge styling + whether
         *     content is embeddable). `text` is embeddable; `image`/`pdf` are badge-only.
         * @enum {string}
         */
        FileKindDto: "text" | "image" | "pdf";
        FileListDto: {
            files: components["schemas"]["FileEntryDto"][];
        };
        /** @description Body of `GET /v1/health`. */
        HealthDto: {
            /** @description `true` once the server has finished boot. */
            ok: boolean;
            /**
             * @description `CARGO_PKG_VERSION` of the running binary.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description Public projection of a `Message`. */
        MessageDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            parts: components["schemas"]["PartDto"][];
            role: components["schemas"]["Role"];
            /** Format: uuid */
            session_id: string;
        };
        /**
         * @description One model entry in the `GET /v1/models` response. Thin HTTP face over
         *     [`ModelInfo`]; `id` is always present, the rest are best-effort
         *     enrichment the upstream catalog may omit.
         */
        ModelDto: {
            /**
             * Format: int32
             * @description Maximum context window in tokens, when advertised.
             */
            context_length?: number | null;
            /** @description Human-readable label when the catalog provides one. */
            display_name?: string | null;
            /** @description Canonical model id used in a turn's `model` field. */
            id: string;
        };
        /**
         * @description Wire mirror of [`openlet_core::types::event::NotificationLevel`].
         * @enum {string}
         */
        NotificationLevelDto: "info" | "warn" | "error";
        /**
         * @description Wire shape for `Part`. Mirrors the domain enum 1:1 but skips the
         *     `Image.bytes` field (images surface via the artifact store URL,
         *     not inline JSON).
         */
        PartDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "text";
            text: string;
        } | {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "reasoning";
            text: string;
        } | {
            args: unknown;
            call_id: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "tool_call";
            name: string;
        } | {
            call_id: string;
            error?: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "tool_result";
            ok: boolean;
            text?: string | null;
        } | {
            artifact_id: string;
            /** Format: int32 */
            height: number;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "image";
            mime: string;
            /** Format: int32 */
            width: number;
        } | {
            artifact_id: string;
            extracted_text?: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "document";
            mime: string;
        } | {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "step_start";
        } | {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "step_finish";
            reason: string;
        } | {
            compacted_message_ids: string[];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "compaction";
            /** Format: int32 */
            original_token_count: number;
            summary: string;
        } | {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "plan";
            plan: string;
        };
        /**
         * @description Resolved-permission outcome on the wire. Mirrors `Decision`'s
         *     `tag = "outcome"` serde shape so allow / deny / pending remain
         *     distinguishable, AND `Deny.feedback` reaches the SSE consumer
         *     (previously collapsed to a bare `"deny"` label).
         *
         *     Note: the `Pending` variant is technically unreachable in
         *     `PermissionResolved` events — those only fire after a decision is
         *     made. It exists here for exhaustive mapping of the domain enum and
         *     to avoid a `panic!` / `unreachable!()` in the conversion path.
         */
        PermissionDecisionDto: {
            /** @enum {string} */
            outcome: "allow";
        } | {
            feedback?: string | null;
            /** @enum {string} */
            outcome: "deny";
        } | {
            /** Format: uuid */
            ask_id: string;
            /** @enum {string} */
            outcome: "pending";
        };
        /**
         * @description Permission mode (per-session, mutable via `POST /v1/session/:id/mode`).
         *
         *     Coarse enum — the full ruleset lives in `permissions.toml`. This is
         *     a session-level column.
         *
         *     Ordering: `ReadOnly < WorkspaceWrite < Danger`. `mode.permits(required)`
         *     returns `true` iff the active mode is at least as permissive as `required`.
         * @enum {string}
         */
        PermissionMode: "read_only" | "workspace_write" | "danger";
        PermissionReplyDto: {
            decision: components["schemas"]["PermissionReplyKind"];
            reason?: string | null;
        };
        /**
         * @description `POST /v1/permission/:ask_id` body.
         *
         *     `decision` mirrors the runtime enum but adds two persisted variants:
         *     `always_allow` and `always_deny` (recorded into `permission_decisions`
         *     so future calls bypass the ask).
         * @enum {string}
         */
        PermissionReplyKind: "allow" | "deny" | "always_allow" | "always_deny";
        /**
         * @description Public shape of a pending permission request emitted in
         *     `permission.asked` events.
         */
        PermissionRequestDto: {
            /** Format: uuid */
            ask_id: string;
            permission: string;
            reason?: string | null;
            /** Format: int64 */
            timeout_ms?: number | null;
        };
        PluginHealthDto: {
            healthy: boolean;
            id: string;
        };
        PluginInfoDto: {
            id: string;
            status: string;
        };
        /** @description `POST /v1/session/:id/prompt_async` ack. */
        PromptAckDto: {
            ack: boolean;
            /** Format: uuid */
            message_id: string;
        };
        /**
         * @description `POST /v1/sessions/:id/question/answer` body. `question_id` matches
         *     the UUIDv7 the `ask_user` tool minted when it suspended; `selected`
         *     is the list of option indices the user picked (single-select carries
         *     exactly one entry, multi-select may carry zero or more).
         */
        QuestionAnswerDto: {
            /** Format: uuid */
            question_id: string;
            selected?: number[];
        };
        /**
         * @description Conversation role. `Tool` carries paired tool-call results.
         * @enum {string}
         */
        Role: "system" | "user" | "assistant" | "tool";
        /**
         * @description Public projection of `SessionMeta`.
         *
         *     `extensions` echoes back the integrator-owned blob set at create
         *     time (or mutated since via `update_session_extensions`). Defaults
         *     to `null` when the session has no extensions.
         */
        SessionDto: {
            /** Format: uuid */
            agent_id: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Slug of the agent profile the session is currently running.
             *     `null` ⇒ the runtime falls back to the default profile
             *     (typically `general`). Plan mode flips this to `plan`.
             */
            current_agent_slug?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            extensions?: Record<string, never>;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_session_id?: string | null;
            permission_mode: components["schemas"]["PermissionMode"];
            /**
             * @description Slug of the profile the session was on before the current
             *     `current_agent_slug` — used by `ExitPlanMode` to restore the
             *     prior profile. `null` for sessions that never switched.
             */
            previous_agent_slug?: string | null;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            updated_at: string;
            version: string;
        };
        /**
         * @description Lifecycle status surfaced via `session.status` events.
         * @enum {string}
         */
        SessionStatus: "idle" | "running" | "cancelling" | "cancelled" | "errored";
        /** @description `POST /v1/session/:id/mode` body. */
        SetModeDto: {
            mode: components["schemas"]["PermissionMode"];
        };
        /**
         * @description Severity ladder: a single Failed flips overall to Failed; a single
         *     Degraded (with no Failed) flips overall to Degraded.
         * @enum {string}
         */
        Status: "healthy" | "degraded" | "failed";
        /**
         * @description Wire-shape token usage summary.
         *
         *     Lossy conversion notes:
         *     - `cache_write_tokens` is the **sum** of the domain type's
         *       `cache_write_tokens` + `cache_creation_input_tokens`. Both represent
         *       cache-write billing; combining them gives consumers a single number
         *       matching what was actually charged.
         *     - `cost_usd` from the domain `Usage` is intentionally dropped here.
         *       Per-step cost surfaces via `StepFinished.cost_decimal_str` instead,
         *       keeping this struct purely about token counts.
         */
        UsageDto: {
            /** Format: int64 */
            cache_write_tokens?: number;
            /** Format: int64 */
            cached_input_tokens: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            reasoning_tokens?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of registered agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preflight report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorReport"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: {
                /** @description Filter to one session */
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of AgentEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Malformed Last-Event-ID header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Case-insensitive substring filter over workspace-relative paths. */
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching workspace files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListDto"];
                };
            };
        };
    };
    content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace-relative path of the file to read. */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content (or unsupported flag) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContentDto"];
                };
            };
            /** @description Absolute path / traversal rejected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider model catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDto"][];
                };
            };
            /** @description Upstream provider error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDto"];
                };
            };
        };
    };
    reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pending ask id */
                ask_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionReplyDto"];
            };
        };
        responses: {
            /** @description Reply accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ask not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered plugins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInfoDto"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginHealthDto"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abort acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbortAckDto"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": string;
            };
        };
        responses: {
            /** @description Attachment accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentAck"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload exceeds 25MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported / unrecognized media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Attachment failed processing pipeline */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compaction dispatched */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompactAckDto"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A turn is already running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages with their parts, in append order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"][];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_mode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetModeDto"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prompt_async: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageDto"];
            };
        };
        responses: {
            /** @description Message accepted; turn dispatched */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptAckDto"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not in a runnable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionAnswerDto"];
            };
        };
        responses: {
            /** @description Answer accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing auth principal */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Question not found or already resolved */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
